package ru.liga.botstate;

public enum BotState {
    INIT,
    WELCOME,
    REGISTER,
    REGISTER_ASK_PASSWORD,
    REGISTER_ASK_CONF_PASSWORD,
    PROFILE_FILLING,
    PROFILE_FILLING_ASK_NAME,
    PROFILE_FILLING_ASK_GENDER,
    PROFILE_FILLING_ASK_DESCRIPTION,
    PROFILE_FILLING_ASK_LOOKING_FOR,
    LOGIN_ASK_PASSWORD,
    IN_MENU,
    SEARCHING,
    ROOT_MENU,
    VIEWING
}
